### ISSUE TITLE
Does not work in inprivate mode

### ISSUE THREAD

**Issue by maiux** [zmni/MSEdge-BlankTab#2]
Hello, I'm using Edge 80.0.361.62 on macOS catalina 10.15.3 (19D76). BlankTab does not work in inprivate mode, even if (obviously) allow in inprivate mode is checked in Extension management.
I also set the NewTabLocation policy via preferences file com.microsoft.Edge.plist (user's preferences)

**Comment by zmni** [comment]
This is a limitation of chrome, as explained on the [manifest page about override](https://developer.chrome.com/extensions/override#:~:text=New%20Tab%20pages%20cannot%20be%20overridden%20in%20incognito%20windows). Only Bookmark Manager and History are allowed to be overridden in incognito/inprivate windows.

**Comment by maiux** [comment]
thanks
